"""Constantes usadas por todo o jogo"""

SCREEN_WIDTH, SCREEN_HEIGHT = 690, 1026

SCROLL_SPEED = 3

SCALE = 3

REAL_FLAPPY_BIRD_WIDTH = 89
REAL_FLAPPY_BIRD_HEIGHT = 24
FLAPPY_BIRD_WIDTH = REAL_FLAPPY_BIRD_WIDTH * SCALE
FLAPPY_BIRD_HEIGHT = REAL_FLAPPY_BIRD_HEIGHT * SCALE

REAL_PLAY_BUTTON_WIDTH = 52
REAL_PLAY_BUTTON_HEIGHT = 29
PLAY_BUTTON_WIDTH = REAL_PLAY_BUTTON_WIDTH * SCALE
PLAY_BUTTON_HEIGHT = REAL_PLAY_BUTTON_HEIGHT * SCALE

REAL_BACKGROUND_WIDTH = 230
REAL_BACKGROUND_HEIGHT = 342
BACKGROUND_WIDTH = REAL_BACKGROUND_WIDTH * SCALE
BACKGROUND_HEIGHT = REAL_BACKGROUND_HEIGHT * SCALE

REAL_GROUND_WIDTH = 180
REAL_GROUND_HEIGHT = 56
GROUND_WIDTH = REAL_GROUND_WIDTH * SCALE
GROUND_HEIGHT = REAL_GROUND_HEIGHT * SCALE

REAL_PIPE_WIDTH = 26
REAL_PIPE_HEIGHT = 270
PIPE_WIDTH = REAL_PIPE_WIDTH * SCALE
PIPE_HEIGHT = REAL_PIPE_HEIGHT * SCALE

REAL_BIRD_WIDTH = 17
REAL_BIRD_HEIGHT = 12
BIRD_WIDTH = REAL_BIRD_WIDTH * SCALE
BIRD_HEIGHT = REAL_BIRD_HEIGHT * SCALE

REAL_TAP_WIDTH = 57
REAL_TAP_HEIGHT = 49
TAP_WIDTH = REAL_TAP_WIDTH * SCALE
TAP_HEIGHT = REAL_TAP_HEIGHT * SCALE

REAL_PAUSE_WIDTH = 13
REAL_PAUSE_HEIGHT = 14
PAUSE_WIDTH = REAL_PAUSE_WIDTH * SCALE
PAUSE_HEIGHT = REAL_PAUSE_HEIGHT * SCALE

REAL_GET_READY_WIDTH = 92
REAL_GET_READY_HEIGHT = 25
GET_READY_WIDTH = REAL_GET_READY_WIDTH * SCALE
GET_READY_HEIGHT = REAL_GET_READY_HEIGHT * SCALE

REAL_GAME_OVER_WIDTH = 91
REAL_GAME_OVER_HEIGHT = 21
GAME_OVER_WIDTH = REAL_GAME_OVER_WIDTH * SCALE
GAME_OVER_HEIGHT = REAL_GAME_OVER_HEIGHT * SCALE

REAL_RESULT_WIDTH = 113
REAL_RESULT_HEIGHT = 57
RESULT_WIDTH = REAL_RESULT_WIDTH * SCALE
RESULT_HEIGHT = REAL_RESULT_HEIGHT * SCALE

REAL_GAME_OVER_BUTTON_WIDTH = 40
REAL_GAME_OVER_BUTTON_HEIGHT = 14
GAME_OVER_BUTTON_WIDTH = REAL_GAME_OVER_BUTTON_WIDTH * SCALE
GAME_OVER_BUTTON_HEIGHT = REAL_GAME_OVER_BUTTON_HEIGHT * SCALE

REAL_NEW_WIDTH = 16
REAL_NEW_HEIGHT = 7
NEW_WIDTH = REAL_NEW_WIDTH * SCALE
NEW_HEIGHT = REAL_NEW_HEIGHT * SCALE


BIRD_POSITION_IN_MENU = (SCREEN_WIDTH / 2 - BIRD_WIDTH / 2, 350)

BIRD_START_POSITION = (SCREEN_WIDTH / 3.5, SCREEN_HEIGHT / 2 - BIRD_HEIGHT)
PIPES_GAP_X = 130
PIPES_GAP_Y = 130

DATA = {}


def load_data():
    """Carregando dados salvos"""
    with open("data.txt", "r") as file:
        rows = file.readlines()
    score = rows[0].split(": ")[1].strip()
    skin = rows[1].split(": ")[1].strip()
    DATA["score"] = int(score)
    DATA["skin"] = skin

